#######################################################################################
# Book settings
title : geosnap User Guide
author: geosnap developers
logo: 'images/logo/geosnap_long.png'

# Information about where the book exists on the web
description: >-
  A brief introduction to Python programming for scientific applications.
#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/executablebooks/quantecon-mini-example
  path_to_book                : "geosnap-guide"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex